server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: info, health, beans

application:
  param-name: "Test Props msg@@@"


messager:
  message: "Hello from Messager Otus Java"